name: Windows Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Boost
      run: |
        # 下载并安装 Boost 库
        $url = "https://sourceforge.net/projects/boost/files/boost/1.70.0/boost_1_70_0.7z/download"
        $output = "boost.7z"
        Invoke-WebRequest -Uri $url -OutFile $output
        
        # 解压 Boost
        7z x boost.7z -o"C:\boost" > $null
        
        # 设置环境变量
        echo "BOOST_ROOT=C:\boost\boost_1_70_0" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        echo "BOOST_LIBRARYDIR=C:\boost\boost_1_70_0\lib64-msvc-14.2" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Install make
      run: choco install make -y

    - name: Build ai.dll
      working-directory: ./ai_src
      run: |
        make LIBS="-lboost_system-mgw62-mt-x64-1_70"
        # 检查是否生成成功
        if (!(Test-Path "../ai.dll")) {
            Write-Error "ai.dll was not created!"
            exit 1
        }

    - name: Build system.exe
      run: |
        make LIBS="-lboost_system-mgw62-mt-x64-1_70"
        # 检查是否生成成功
        if (!(Test-Path "system.exe")) {
            Write-Error "system.exe was not created!"
            exit 1
        }

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: |
          system.exe
          ai.dll
