name: Windows Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BOOST_VERSION: 1.70.0
  BOOST_ROOT: C:\local\boost_${{ env.BOOST_VERSION }}

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache Boost
      id: cache-boost
      uses: actions/cache@v2
      with:
        path: ${{ env.BOOST_ROOT }}
        key: boost-${{ env.BOOST_VERSION }}

    - name: Install Boost (if not cached)
      if: steps.cache-boost.outputs.cache-hit != 'true'
      run: |
        Invoke-WebRequest -Uri "https://sourceforge.net/projects/boost/files/boost/${{ env.BOOST_VERSION }}/boost_${{ env.BOOST_VERSION//./_ }}-msvc-14.1-64.exe/download" -OutFile boost.exe
        Start-Process -Wait -FilePath .\boost.exe -ArgumentList "-o${{ env.BOOST_ROOT }}\.. -y"
        del boost.exe

    - name: Set up environment
      run: |
        echo "BOOST_ROOT=${{ env.BOOST_ROOT }}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        echo "BOOST_LIBRARYDIR=${{ env.BOOST_ROOT }}\lib64-msvc-14.1" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Build ai.dll
      working-directory: ai_src
      run: make

    - name: Build system.exe
      run: make

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: windows-binaries
        path: |
          system.exe
          ai.dll
