name: Build akochan on Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install Boost
      run: |
        # 下载并安装 Boost
        $url = "https://sourceforge.net/projects/boost/files/boost/1.82.0/boost_1_82_0-msvc-14.3-64.exe/download"
        $output = "$env:TEMP\boost_setup.exe"
        Invoke-WebRequest -Uri $url -OutFile $output
        Start-Process -FilePath $output -ArgumentList "/VERYSILENT", "/SUPPRESSMSGBOXES", "/NORESTART", "/SP-", "/DIR=C:\boost" -Wait
        
        # 设置 Boost 环境变量
        echo "BOOST_ROOT=C:\boost" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        echo "BOOST_LIBRARYDIR=C:\boost\lib64-msvc-14.3" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Install build tools
      run: |
        # 安装必要的构建工具
        choco install make -y
        choco install mingw -y

    - name: Build with Makefile
      run: |
        # 使用 Makefile 构建
        make
        # 如果 make 命令不是默认的，可能需要指定具体的 make 程序路径
        # 例如: C:\ProgramData\chocolatey\bin\make.exe

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: akochan-build
        path: |
          *.exe
          *.dll
