name: Build akochan on Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install Boost
      run: |
        # 下载 Boost 二进制 ZIP 包
        $boostVersion = "1.82.0"
        $boostUrl = "https://boostorg.jfrog.io/artifactory/main/release/$boostVersion/binaries/boost_$($boostVersion.Replace('.','_'))-msvc-14.3-64.zip"
        $output = "$env:TEMP\boost.zip"
        
        # 使用 TLS 1.2 协议下载
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
        Invoke-WebRequest -Uri $boostUrl -OutFile $output
        
        # 解压到 C:\boost
        Expand-Archive -Path $output -DestinationPath C:\boost
        
        # 设置 Boost 环境变量
        echo "BOOST_ROOT=C:\boost" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        echo "BOOST_LIBRARYDIR=C:\boost\lib64-msvc-14.3" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Install build tools
      run: |
        # 安装必要的构建工具
        choco install make -y
        choco install mingw -y

    - name: Build with Makefile
      shell: cmd
      run: |
        # 使用 Makefile 构建
        make

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: akochan-build
        path: |
          *.exe
          *.dll
